[workspace]
resolver = "2"
members = [
    "crates/uparser-core",
    "crates/uparser-napi",
    "crates/uparser-python",
    "crates/uparser-native-engine",
    "crates/uparser-document-engine",
]

[workspace.package]
edition = "2024"
license = "UNLICENSED"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"
